version: "3"
services: 
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    volumes: 
      - ./opt/adguardhome:/opt/adguardhome/work
      - ./opt/adguardhome/conf:/opt/adguardhome/conf
    ports: 
      - 553:553/tcp
      - 553:553/udp 
      - 67:67/udp 
      - 68:68/tcp 
      - 68:68/udp 
      - 3080:80/tcp 
      - 3443:443/tcp 
      - 853:853/tcp 
      - 3000:3000/tcp
   restart: unless-stopped
